### ISSUE TITLE
[HxNav] To add new Underlined variant

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#534]
We need to implement new NavVariant.Underlined to V4
https://getbootstrap.com/docs/5.3/components/navs-tabs/#underline

```[tasklist]
### Tasks
- [x] Create branch feature/NavVariant.Underlined
- [x] Introduce new value Underlined = 3 to NavVariant.cs enum
- [x] Edit GetVariantCssClass so it returns "nav-underline" for NavVariant.Underlined
- [x] Add new demo to /HxTabPanelDoc/Havit.Blazor.Components.Web.Bootstrap.Documentation.razor
```
